config/routes.rb
Rails.application.routes.draw do
  root 'pages#about'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'projects' => 'pages#projects'
  get 'races' => 'races#show'
  get 'addRace' => 'races#new'

  resource :pages
  resource :races
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/race.rb
class Race < ApplicationRecord
  validates :raceName, presence: true
  validates :time, presence: true
  validates :distance, presence: true
  validates :averagePace, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def projects
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  def show
    @raceData = Race.all.order(created_at: :desc)
    @raceLabelArray = ["Time", "Distance", "Average Pace"]
  end

  def new
    @race = Race.new
  end

  def create
    @race = Race.new(race_params)
    if @race.save
      #Successful save
      redirect_to races_url
    else
      render 'new'
    end
  end

  private
    def race_params
      params.require(:race).permit(:raceName, :time, :distance, :averagePace)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carter Markegard</title>
    <%= stylesheet_link_tag "partials/navbar.css"%>
    <%= favicon_link_tag asset_path("favicon.ico") %>
    <link href="https://fonts.googleapis.com/css?family=Abel&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="Container">
      <nav>
        <div class="navBar">
          <h1 class="centered_name"><%= link_to "CARTER MARKEGARD", root_path%></h1>
        </div>
        <ul class="tabs">
          <li class="tab" ><%= link_to "About", root_path%></li>
          <li class="tab"><%= link_to "Contact", contact_path%></li>
          <li class="tab"><%= link_to "Projects", projects_path%></li>
          <li class="tab"><%= link_to "Races", races_path%></li>
          <li class="tab"><%= link_to "Add Race", addRace_path%></li>
        </ul>
        <div class="burger">
          <div class="line1"></div>
          <div class="line2"></div>
          <div class="line3"></div>
        </div>
      </nav>

      <%= javascript_include_tag 'navBar' %>
      <div class="Content">
        <%= yield %>
      </div>

      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= stylesheet_link_tag "pages/about"%>
</head>
<body>
  <div class="IntroText">
    <h1 class="Title">Howdy, I'm <span class="Name">Carter Markegard</span></h1>
    <h2 class="Description">
      I use science and technology to create amazing things.
    </h2>
  </div>
  <div class="Headshot">
    <%= image_tag("carter.jpg", alt: "A stock picture of a professional.") %>
  </div>
  <div>
    <h3>
      I'm a third year computer science and physics double major
      that loves to make things. I believe that all work should
      benefit humanity, and that technology is our best tool yet.
    </h3>
  </div>
</body>
</html>

app/views/pages/contact.html.erb
<html lang="en">
  <head>
    <%= stylesheet_link_tag "pages/contact" %>
  </head>
  <body>
    <h1 class="email">Email Me!</h1>
    <h2>CarterMarkegardPortfolio@gmail.com</h2>
  </body>
</html>

app/views/pages/projects.html.erb
<html lang="en">
  <head>
    <%= stylesheet_link_tag "pages/projects"%>
  </head>
  <body>
    <h1>
      Carter's Projects
    </h1>
    <div class="ProjectContainer">
      <div class="infoCard">
        <h3> Engineering / Software Development Internship</h3>
        <%= image_tag("tpi.jpg", alt: "Rcoket Ship") %>
        <p> I used agile design to build applications that streamlined quality-department metrics and
          automated saftey data entry and analysis.
        </p>
      </div>
      <div class="infoCard">
        <h3> GPU Based Password Cracker</h3>
        <%= image_tag("gpu.jpg", alt: "Rcoket Ship") %>
        <p>
          As an investigation into password security, Chase Snodgras and I built
          a GPU-based password cracking software that can crack an 8-digit special character combination
          in 22 seconds on outdated hardware.
        </p>
      </div>
      <div class="infoCard">
        <h3>Local Foods Connection Website</h3>
        <%= image_tag("LFS_Logo.png", alt: "Rcoket Ship") %>
        <p>
          Local Foods Connection (LFC) is a non-profit
          that connects low-income households with local food. My team and I
          created a web applicaiton that allows users to search for food amoung
          a database of local farmers.
        </p>
      </div>
      <div class="infoCard">
        <h3>Custom Speaker Building</h3>
        <%= image_tag("speaker.jpg", alt: "Rcoket Ship") %>
        <p>
          I've built speakers large and small by teaching myself electronics
          and carpentry.
        </p>
      </div>
    </div>
  </body>
</html>

app/views/races/new.html.erb
<!DOCTYPE html>
<head>
  <%= stylesheet_link_tag "newRace", media: 'all', 'data-turbolinks-track' => true%>
  <link href="https://fonts.googleapis.com/css?family=Abel&display=swap" rel="stylesheet">
</head>
<body>
  <div class="form">
    <p class="title"> Add a new race </p>
      <%= form_for(@race) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :raceName, "Race Name" %>
        <%= f.text_field :raceName, class: 'form-control'%>

        <%= f.label :time, "Time" %>
        <%= f.text_field :time, class: 'form-control'%>

        <%= label :distance, "Distance" %>
        <%= f.text_field :distance, class: 'form-control'%>

        <%= f.label :averagePace, "Average Pace" %>
        <%= f.text_field :averagePace, class: 'form-control'%>

        <%= f.submit "Add Race", class: "btn btn-primary" %>
      <% end %>
  </div>

  <!--
  <div class="form">
    <p class="title"> Add a new race </p>
    <form action="/races" method="post">
      <p class="fieldTitle">Race Name</p><br>
      <input type="text" name="raceName"><br>

      <p class="fieldTitle">Time</p><br>
      <input type="text" name="raceTime"><br>

      <p class="fieldTitle">Distance</p><br>
      <input type="radio" name="distance"><br>

      <p class="fieldTitle">Average Pace</p><br>
      <input type="text" name="averagePace"><br>

      <input type="submit" name="submit" value="Submit">
    </form>
  </div>
  -->
</body>

app/views/races/show.html.erb
<!DOCTYPE html>
<head>

</head>
<body>
  <H1 class="raceTitle">
    Carter's Race Times
    <div class="raceTable">
      <table>
        <tr>
          <% for i in 0..@raceLabelArray.length do %>
            <td><%= @raceLabelArray[i] %></td>
          <% end %>
        </tr>
        <% @raceData.each do |race|%>
          <tr class="raceName">
            <td colspan="3"><%= race.raceName %></td>
          </tr>
          <tr>
            <td><%= race.time %></td>
            <td><%= race.distance %></td>
            <td><%= race.averagePace %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </H1>
</body>

app/views/shared/_error_messages.html.erb
<!--
  This is a partial that builds the error messages for the newRace form
-->

<% if @race.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(@race.errors.count, "error") %>.
  </div>
  <ul>
  <% @race.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <%= stylesheet_link_tag 'partials/footer.css' %>
  <div class="footer">
    <p>Carter Markegard</p>
  </div>
</footer>